# These are supported funding model platforms
github: # 中国大陆暂不支持，留空或忽略
patreon: # 如果有 Patreon，可替换为用户名
open_collective: # 如果有 Open Collective，可替换为用户名
ko_fi: # 如果有 Ko-fi，可替换为用户名
tidelift: # 如果有 Tidelift，可替换为 platform-name/package-name
community_bridge: # 如果有 Community Bridge，可替换为 project-name
liberapay: # 如果有 Liberapay，可替换为用户名
issuehunt: # 如果有 IssueHunt，可替换为用户名
lfx_crowdfunding: # 如果有 LFX Crowdfunding，可替换为 project-name
polar: # 如果有 Polar，可替换为用户名
buy_me_a_coffee: # 如果有 Buy Me a Coffee，可替换为用户名
thanks_dev: # 如果有 thanks.dev，可替换为用户名
custom: 
  - "https://github.com/lintsinghua/lintsinghua.github.io/issues/1"
